DROP TABLE IF EXISTS outer_orders;
CREATE TABLE outer_orders (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(12) NOT NULL,
  type VARCHAR(3) NOT NULL,
  pair_from VARCHAR(6) NOT NULL,
  pair_to VARCHAR(6) NOT NULL,
  amount DOUBLE(32, 16) NOT NULL,
  rate DOUBLE(32, 16) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;