DROP TABLE IF EXISTS outer_orders;
CREATE TABLE outer_orders (
  Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(12) NOT NULL,
  Type VARCHAR(6) NOT NULL,
  PairFrom VARCHAR(6) NOT NULL,
  PairTo VARCHAR(6) NOT NULL,
  Amount DOUBLE(32, 16) NOT NULL,
  Rate DOUBLE(32, 16) NOT NULL,
  OrderId VARCHAR(64) UNIQUE NOT NULL,
  Status VARCHAR(6) NOT NULL DEFAULT 'opened',
  CreatedAt TIMESTAMP NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;